### ISSUE TITLE
Convert O*NET dataset to cube architecture

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#1]
* [x] Ingest ONET Data
* [x] Create Schema

**Comment by hwchen** [comment]
- [ ] add rca
- [ ] add overall value (combine IM and LV)

**Comment by hwchen** [comment]
hwchen [1:51 PM]
@jspeiser I'm working on onet rca. Did you want it as share of occupations per skill or share of skill per occupations? Or both? I also remember that we had discussed getting a total score calculated member; I think we had discussed just multiplying the IM and LV
jspeiser [1:54 PM]
re total score: yeah I think just multiplying the two should suffice
re rca: 1) we want it as the RCA so that the index is occupation and you are looking at for each skill: how important is this skill to this occupation? 2) we'll also need the same swapping occupation for CIP
so I believe that would be RCA as : skill_val_for_this_skill_for_this_occ / skill_val_total_for_this_occ vs skill_val_this_skill_all_occs / all_skill_vals (edited)
(and similar for CIP)
does that make sense?
hwchen [2:00 PM]
yep, thans
jspeiser [2:01 PM]
basically at the end of the day we'll need to form these vizs: https://datausa.io/profile/soc/2310XX/#skills
Data USAData USA
Lawyers, & judges, magistrates, & other judicial workers
Lawyers, & judges, magistrates, & other judicial workers are most often employed by the Legal services industry. The average yearly wage for Lawyers, & judges, magistrates, & other judicial workers was $151,638 in 2015. The top 3 most similar occupations to Lawyers, & judges, magistrates, & other judicial workers by wage are Podiatrists, Nurse anesthetists and Chief executives & legislators. Lawyers, & judges, magistrates, & other judicial workers are part of the Legal Occupations category, along with Legal Occupations; Judicial law clerks; Paralegals & legal assistants; and Miscellaneous legal support workers.
http://yellowhammer.datausa.io/static/img/splash/soc/2310XX.jpg
hwchen [2:01 PM]
ah, I understand now, that's helpful
jspeiser [2:01 PM]
https://datausa.io/profile/cip/110701/#skills
Data USAData USA
Computer Science
The locations with the highest concentration of Computer Science graduates are Los Angeles, CA, New York, NY and Chicago, IL. The locations with a relatively high number of Computer Science graduates are Fairfield, IA, Warrensburg, MO and Hoboken, NJ. The most common degree awarded to students studying Computer Science is a Bachelor's Degree.
http://yellowhammer.datausa.io/static/img/splash/cip/110701.jpg
(the values may come out different that ok, but the overall ranking of skills should be similar)
one thing I just noticed looking at Data USA -- in Data USA we have 2 levels of skill hierarchy
would we be able to add the parent hierachy to the cube? e.g. https://api.datausa.io/attrs/skill/
(it is also possible that there are new or delete skills ... but basically we will need a way to group them
hwchen [2:22 PM]
It shouldn't be a problem. But I guess it's not clear to me from your link what the hierarchy is.
jspeiser [2:23 PM]
might be easier to see this way...
jspeiser [2:23 PM]
added this CSV snippet: skill.csv 

"id","name","avg_value","parent"

"2.B.3.a","Operations Analysis",1.9774097,"System Skills"

"2.B.3.b","Technology Design",1.3338959,"System Skills"

"2.B.3.c","Equipment Selection",1.417362,"System Skills"

"2.B.3.d","Installation",0.8114915,"System Skills"

jspeiser [2:23 PM]
basically each skill belongs to a parent group (edited)
hwchen [2:23 PM]
Ah, that makes more sense. So I just have to figure out where to slice the id

**Comment by jspeiser** [comment]
I think you meant @jspeis ;)

I have absolutely no idea what's going on, but you should do both.

**Comment by hwchen** [comment]
Whoops! :)
